name: thelabgeek
description: An native application that is indisposable for the modern scientist.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true